### ISSUE TITLE
email verification send promise rejected

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#107]
If i type verification code manually the next email (ie backup email) is sent correctly
```
{"level":50,"time":1572188601330,"pid":23,"hostname":"8309af1d-ee76-47de-a835-7b2e85276236","name":"GoodDollar - Server","from":"Mautic","msg":"Mautic Error: /emails/4/contact/5151/send Request Timeout {\"body\":{\"tokens\":{\"code\":\"145177\",\"firstName\":\"hadar ro\"}}}","v":1}
2019-10-27T15:03:21.331592+00:00 app[web.1]: Unhandled Rejection at: Promise {
2019-10-27T15:03:21.331595+00:00 app[web.1]:   <rejected> Error: Request Timeout
2019-10-27T15:03:21.331596+00:00 app[web.1]:       at Promise (/app/dist/server.js:1:16492)
2019-10-27T15:03:21.331597+00:00 app[web.1]:       at new Promise (<anonymous>)
2019-10-27T15:03:21.331598+00:00 app[web.1]:       at ue (/app/dist/server.js:1:16457)
2019-10-27T15:03:21.3316+00:00 app[web.1]:       at Object.baseQuery (/app/dist/server.js:1:16719)
2019-10-27T15:03:21.331602+00:00 app[web.1]:       at Object.sendVerificationEmail (/app/dist/server.js:1:17319)
2019-10-27T15:03:21.331603+00:00 app[web.1]:       at e.post.H (/app/dist/server.js:1:39418)
2019-10-27T15:03:21.331605+00:00 app[web.1]:       at process._tickCallback (internal/process/next_tick.js:68:7) } reason: Error: Request Timeout
2019-10-27T15:03:21.331606+00:00 app[web.1]:     at Promise (/app/dist/server.js:1:16492)
2019-10-27T15:03:21.331608+00:00 app[web.1]:     at new Promise (<anonymous>)
2019-10-27T15:03:21.331609+00:00 app[web.1]:     at ue (/app/dist/server.js:1:16457)
2019-10-27T15:03:21.33161+00:00 app[web.1]:     at Object.baseQuery (/app/dist/server.js:1:16719)
2019-10-27T15:03:21.331612+00:00 app[web.1]:     at Object.sendVerificationEmail (/app/dist/server.js:1:17319)
2019-10-27T15:03:21.331613+00:00 app[web.1]:     at e.post.H (/app/dist/server.js:1:39418)
2019-10-27T15:03:21.331615+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
```

Definition of Done
---
- [x] verification email sent correctly
- [ ] catch promise rejection, log error, return error - error should show as popup on dapp

**Comment by sirpy** [comment]
fixed. was an error in mautic template
