### ISSUE TITLE
(Bug) Server logs missing request id and throw exception

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#250]
- [x] we used to print a request id with each server log where relevant (we generated a random id), its missing
- [x] on "next" there are exceptions "cannot read error of undefined"

**Comment by serdiukov-o-nordwhale** [comment]
@sirpy 
"cannot read error of undefined" it's internal error of the expressjs, it comes from process_params in lib/routes files.
it appears somethime during Gun.serve middleware execution. i tried but was unable to find an exact reason yet. 
for now i wrapped Gun.serve onto try..catch, removed returns from the app.use callback and added logging. Probably this solves the issue or logs added could help finding the reason.

Here short summary of the clues i found:
Probably you could also look on that and find something else.

Stack:
```
TypeError: Cannot read property 'error' of undefined
    at Fi.e.use (/app/dist/server.js:1:110984)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10) 
```

Fi.e.use (/app/dist/server.js:1:110984) is:
```
if (conf.gundbServerMode) { app.use(Gun.serve) }
```

the 'error' access attempt is here (node_modules/express/lib/router/index.js line 375):
```
// param previously called with same value or error occurred
    if (paramCalled && (paramCalled.match === paramVal
      || (paramCalled.error && paramCalled.error !== 'route'))) {
      // restore value
      req.params[name] = paramCalled.value;

      // next param
      return param(paramCalled.error); // <-- HERE
    }

    called[name] = paramCalled = {
      error: null,
      match: paramVal,
      value: paramVal
    };

    paramCallback();
  }
```

**Comment by serdiukov-o-nordwhale** [comment]
@sirpy after more detailed research i found that this message is always prepended with:
406 <158>1 2020-09-10T12:04:30.511651+00:00 heroku router - - sock=client at=warning code=H27 desc="Client Request Interrupted" method=PUT path="/verify/face/6cA12A51a8DCf70DDf5Ad502096105Af67cFAdc0" host=goodserver.gooddollar.org request_id=61dad0ab-b7c8-4589-a37a-2d3818c115bc fwd="27.247.0.106" dyno=web.1 connect=0ms service=42807ms status=499 bytes=0 protocol=https
I found some info about that error here: https://help.heroku.com/VX2J01DE/why-do-h27-errors-happen

This happens when Zoom reaches some internal timeout dedicated for send enrollment request and we should cancel pending axios request. That issue happened on the heroku router level which is upper that app layer and it's seems isn't possible to be caught

I reproduced that case locally - without heroku no 'TypeError: Cannot read property 'error' of undefined' appears.
When we're cancelling XMLHTTPRequest, the request won't be logged (becasuse we're listening to req.on('finish')), so there're no logs about that error. 
I looked over all code executing during FV on server and haven't find any place where we're trying to access <someobject>.error.
So i still don't know where and why the error is actually thrown. 

Most like the place is the express router, like i found before and that's an issue related to running node apps over heroku. I'll try to find out why it's happening tomorrow. But, regarding the case when the issue appears - it's not critical, because if Zoom reached timeout that means user anyway have to pass FV again.

**Comment by serdiukov-o-nordwhale** [comment]
As i supposed in FV all common steps (check for dup -> enroll -> whitelist) are taking most time. The bottleneck is interacting from the external API / sending whiltelist tx to wallet:
```
// search
2020-09-12T11:30:49.463Z - workerId:undefined - debug (FROM /verify/face/412F9E26ed65161ea3945d7F7c982aa7dBAC6A16 ): {"uuid":"afCz5oQaY5","message":"Received response from Zoom API:","context":[{"responseTime":3932,"meta":{"ok":true,"code":200,"mode":"dev","m":{"zb":2220,"zp":2444,"zw":2458,"st":1599910246.491911,"bt":1995},"message":"The search request was processed successfully.","results":[{"enrollmentIdentifier":"d8f592cbfa53622a9f63c34ba28392246bc885a3","matchLevel":10}],"sourceFaceMap":{"isReplayFaceMap":false}},"data":{"results":[{"enrollmentIdentifier":"d8f592cbfa53622a9f63c34ba28392246bc885a3","matchLevel":10}],"sourceFaceMap":{"isReplayFaceMap":false}}}]}

// enroll
2020-09-12T11:30:51.256Z - workerId:undefined - debug (FROM /verify/face/412F9E26ed65161ea3945d7F7c982aa7dBAC6A16 ): {"uuid":"afCz5oQaY5","message":"Received response from Zoom API:","context":[{"responseTime":1790,"meta":{"ok":true,"code":200,"mode":"dev","m":{"bt":661,"zb":1302,"zp":1318,"zw":1335,"st":1599910249.820454},"message":"The FaceMap was successfully enrolled.","auditTrailVerificationMessage":"ZoOm determined the Audit Trail Image came from the same session as the FaceMap.","auditTrailVerificationStatus":0,"createdDate":"2020-09-12T11:30:50+00:00","enrollmentIdentifier":"412f9e26ed65161ea3945d7f7c982aa7dbac6a16","errorMessageFromZoomServer":null,"errorStatusFromZoomServer":0,"faceMapType":0,"glasses":false,"isEnrolled":true,"isLowQuality":false,"isReplayFaceMap":true,"livenessStatus":0,"retryReason":0},"data":{"auditTrailVerificationMessage":"ZoOm determined the Audit Trail Image came from the same session as the FaceMap.","auditTrailVerificationStatus":0,"createdDate":"2020-09-12T11:30:50+00:00","enrollmentIdentifier":"412f9e26ed65161ea3945d7f7c982aa7dbac6a16","errorMessageFromZoomServer":null,"errorStatusFromZoomServer":0,"faceMapType":0,"glasses":false,"isEnrolled":true,"isLowQuality":false,"isReplayFaceMap":true,"livenessStatus":0,"retryReason":0}}]}

// wallet tx
2020-09-12T11:30:55.753Z - workerId:undefined - debug (FROM AdminWallet ): {"message":"send whitelist tx finished in 4379ms","context":[]}
```

Regarding wallet - here's detailed logs of this process:
```
2020-09-12T11:30:51.306Z - workerId:undefined - debug (FROM AdminWallet ): {"message":"call isWhitelisted finished in 40ms","context":[]}
2020-09-12T11:30:51.370Z - workerId:undefined - debug (FROM AdminWallet ): {"message":"call lastAuthenticated finished in 61ms","context":[]}
2020-09-12T11:30:51.371Z - workerId:undefined - debug (FROM AdminWallet ): {"message":"create whitelist tx finished in 0ms","context":[]}
2020-09-12T11:30:51.458Z - workerId:undefined - debug (FROM AdminWallet ): {"message":"getting tx lock:","context":[{"uuid":"tQEsx0A="}]}
2020-09-12T11:30:51.458Z - workerId:undefined - debug (FROM wallet queueMutex ): {"message":"lock request","context":[{"addresses":["0x405D45D736CEb649E47f8044e6Fca15ECCFcf0e8","0x9EB0c3Eb6B58A86e0B6d79340aDcE44ce7A14733","0xfc1a99a3Dd4E7e757e384E1f134fa3361324cfCb","0x200044AdC24aA94213e75bfbA6183d5A17654aEC","0x1187a51D10d362AF03d4E0a0002Dc53c71978BB4","0x021243C93E71cff6cf2FD387cb0A63304BDD8a34","0xFde9f61733eEE5587916b49d146C5fe82916c41b","0x933ed924eDD6a54196D26E7308F7264f1c7350A3","0x122dC89067d5D8570ab0f8176bF8544E1BbeBCD5","0x83FD2A84E492c1b6D9A6C3B1780F41CeE28c212C"]}]}
2020-09-12T11:30:51.569Z - workerId:undefined - debug (FROM wallet queueMutex ): {"message":"getFirstFreeAddress: address not locked","context":[{"address":"0xFde9f61733eEE5587916b49d146C5fe82916c41b"}]}
2020-09-12T11:30:51.569Z - workerId:undefined - debug (FROM wallet queueMutex ): {"message":"lock: got wallet","context":[{"address":"0xFde9f61733eEE5587916b49d146C5fe82916c41b","wallet":{"address":"0xFde9f61733eEE5587916b49d146C5fe82916c41b","nonce":610,"mutex":{"_locking":{},"_locks":0}}}]}
2020-09-12T11:30:51.570Z - workerId:undefined - debug (FROM wallet queueMutex ): {"message":"lock: acquired lock","context":[{"address":"0xFde9f61733eEE5587916b49d146C5fe82916c41b"}]}
2020-09-12T11:30:51.570Z - workerId:undefined - debug (FROM AdminWallet ): {"message":"got tx lock:","context":[{"uuid":"tQEsx0A=","address":"0xFde9f61733eEE5587916b49d146C5fe82916c41b"}]}
2020-09-12T11:30:51.613Z - workerId:undefined - debug (FROM AdminWallet ): {"message":"sending tx from: 0xFde9f61733eEE5587916b49d146C5fe82916c41b | nonce: 610","context":[{"uuid":"tQEsx0A=","balance":"6645563000000000","gas":410986,"gasPrice":"1000000000"}]}
2020-09-12T11:30:51.658Z - workerId:undefined - debug (FROM AdminWallet ): {"message":"got tx hash:","context":
2020-09-12T11:30:55.752Z - workerId:undefined - debug (FROM AdminWallet ): {"message":"got tx receipt:","context":[{"uuid":"tQEsx0A="}]}
2020-09-12T11:30:55.753Z - workerId:undefined - debug (FROM AdminWallet ): {"message":"send whitelist tx finished in 4379ms","context":[]}
```
to get more detailed info we could also add profiling to sendTransaction and also probably check what happens on the contracts side and why they executes too much time.

Regarding FV - we have to check fvqa logs, probably read some docs regarding zoom server how to speed up it. probably there's need to add some indexes to database, enable caching etc

other final steps (whitelist in claim queue, update user are finished much faster:
```
2020-09-12T11:31:07.466Z - workerId:undefined - debug (FROM /verify/face/412F9E26ed65161ea3945d7F7c982aa7dBAC6A16 ): {"uuid":"wp4Qb5006t","message":"Set allowed in queue finished in 2ms","context":[]}
2020-09-12T11:31:07.491Z - workerId:undefined - debug (FROM /verify/face/412F9E26ed65161ea3945d7F7c982aa7dBAC6A16 ): {"uuid":"wp4Qb5006t","message":"Update user finished in 26ms","context":[]}
```

**Comment by serdiukov-o-nordwhale** [comment]
If we'll unable to solve the issue server-side we'll have to change FV flow:
- add endpoint for just to quickly test liveness
- in zoom callback sent request to it
- split current fv flow onto 3 endpoints a) check for dups b) enroll c) whitelist
- get facemap from the zoom session result and post it onto those dup endpoint, then (if no dup) to enroll then (if success) call whitelist
- show an additional screen (existing FV screen could take this role) an check list (as we had before) where user could see updating statuses (checking for duplicates.... OK, enrolling your face... OK, whitelkisting your account...OK)
- on any error showing error mark for corresponding step, waiting ~0.5-1sec and redirecting user to the corresponding error screen

**Comment by serdiukov-o-nordwhale** [comment]
regarding topwallet - you could use getProfiler function i've added to profile this endpoint. But i think the issue will be the same like with whitelisting - the long transaction processing.
