### ISSUE TITLE
(Bug) Sending paused for this account at /verify/sendemail

### ISSUE THREAD

**Issue by johnsmith-gooddollar** [GoodDollar/GoodServer#419]
@sirpy looks like something wrong with our AWS account - we've been banned or reached some threshold ?

```
2023-04-12 05:11:51.532 
Open surrounding logs from goodserver_next
Hold CMD for a new tab 
[goodserver_next] web.1 2023-04-12T02:11:51.532Z - workerId:1 - error (FROM: /verify/sendemail userId: ): {"uuid":"wJfDqX0IOH","message":"failed sending email verification to user:","context":["Sending paused for this account. For more information, please check the inbox of the email address associated with your AWS account.",{"type":"Error","message":"Sending paused for this account. For more information, please check the inbox of the email address associated with your AWS account.","stack":"MessageRejected: Sending paused for this account. For more information, please check the inbox of the email address associated with your AWS account.\n    at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/query.js:50:29)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:686:14)\n    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:688:12)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:686:14)\n    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)","code":"MessageRejected","time":"2023-04-12T02:11:51.531Z","requestId":"d7394c9d-9b5d-425f-9bcc-231d82341e50","statusCode":400,"retryable":false,"retryDelay":33.22178676653795},{"userRec":{"email":"Santanadih1@gmail.com","fullName":"Diego Santana","mobile":"","smsValidated":false,"isEmailConfirmed":false,"skipEmail":false,"skipPhone":true,"skipSMS":true,"skipEmailConfirmation":false,"skipMagicLinkInfo":true,"torusProvider":"facebook","lastStep":3,"finished":false,"loggedInAs":"0x790a5c272d35123f692e4f93f7362b96d8533fcf","gdAddress":"0x7a485f61c112b3ab6bf7940fee9bebce2bb57dfa","profilePublickey":"bbaareifyhxef4efj4s3nre4jwrmbreho7nwagr6bm7vc7bw7wpf7tywoom","exp":1681269060,"aud":"unsigned","sub":"0x790a5c272d35123f692e4f93f7362b96d8533fcf","iat":1681265460,"_id":"64361334f7e6a302a0570a4e","identifier":"0x790a5c272d35123f692e4f93f7362b96d8533fcf","__v":0,"isCompleted":{"topWallet":false,"whiteList":false},"isVerified":false,"lastLogin":"2023-04-12T02:11:00.301Z","trustIndex":"2023-04-12T02:11:00.302Z"},"code":"983922"}]} 
```

https://logtail.com/team/133314/tail?a=1681265511532.45022576&v=61125&redirected=true&rf=1681252750000&rt=1681274350000&q=%22-%20error%20(%22

**Comment by sirpy** [comment]
switched to a new account for now. tiago is working to restore it.
