### ISSUE TITLE
(Bug) CeloAdminWallet tx timeout

### ISSUE THREAD

**Issue by johnsmith-gooddollar** [GoodDollar/GoodServer#420]
Looks related to this hot fix: https://github.com/GoodDollar/GoodServer/commit/ab0fba6dcde1f994161c5358ad08704dc9db8cf4

_May be_ fixed via #414 / https://github.com/GoodDollar/GoodDAPP/pull/3909 as timeout is one of conditions for the fallback to another RPC:

https://github.com/GoodDollar/GoodServer/commit/d0850fb87c19272e919f3822ebd88c0a18ae8179#diff-eb07daa442eadcdab87028ae408396ad0a0ad089ac0bb0b0c16c0457fda4b00aR12

```
2023-04-12 23:32:31.746 [goodserver_next] web.1 2023-04-12T20:32:31.745Z - workerId:2 - error (FROM: /verify/topWallet userId: ): {"uuid":"6sXojjzN6z","message":"sendTransaction error:","context":["Request timeout: CeloAdminWallet tx timeout",{"type":"Error","message":"Request timeout: CeloAdminWallet tx timeout","stack":"Error: Request timeout: CeloAdminWallet tx timeout\n    at c (/app/dist/server.js:1:25375)\n    at async l (/app/dist/server.js:1:25448)\n    at async L.sendTransaction (/app/dist/server.js:1:40998)\n    at async L.topWallet (/app/dist/server.js:1:36233)\n    at async /app/dist/server.js:1:110114"},{"from":"0x90731520956506875dA0517Fc315a6b334dBfDa6","currentNonce":16380,"netNonce":16380,"txuuid":"kzFAJeU=","txHash":"0xafee985056b8c9360c07f3ec3e0e36c3dd76a41318b7d7ca56af3b672fa5989b","retry":true,"wallet":"CeloAdminWallet","network":42220}]} 
```

**Comment by johnsmith-gooddollar** [comment]
@vldkhh I think we need to release #414 to QA (+corresponging web app PR) and test it properly
then release wallet app PROD.

could we test till the end of this week ? I want to release tomorrow

**Comment by L03TJ3** [comment]
@johnsmith-gooddollar I cannot find this in error logs when I look at goodserver prod (filtered on last 60 days)

Could be closed?

**Comment by johnsmith-gooddollar** [comment]
@L03TJ3 its related to GoodDApp not the server
check at sentry please, or ask @vldkhh to do it
